controller_list:
  - name: fake_f_arm_controller
    joints:
      - joint1_f
      - joint2_f
  - name: fake_b_arm_controller
    joints:
      - joint1_b
      - joint2_b
  - name: fake_f_eef_controller
    joints:
      []
  - name: fake_b_eef_controller
    joints:
      []