f_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.5
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 30
  position_only_ik: True
b_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.5
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 30
  position_only_ik: True